src/app/teams/teams.service.ts

New membership ID

---

firestore.rules
src/app/quests/quest.d.ts
src/app/quests/quest.service.ts

Closes #13

---

src/app/teams/teams.service.ts
src/app/ui/user-profile/user-profile.component.html
src/app/ui/user-profile/user-profile.component.ts

moved changes from old branch to here, a squash

---

src/app/ui/user-profile/user-profile.component.html

fix team name not appearing

---

firestore.rules
src/app/ui/user-profile/user-profile.component.html
src/app/ui/user-profile/user-profile.component.ts

committing changes for the view member issue

closes #28

---

src/app/core/auth.guard.ts
src/app/core/auth.service.ts
src/app/quests/index.ts
src/app/quests/quest.service.ts
src/app/ui/dialog/add-quest-dialog/add-quest-dialog.component.html
src/app/ui/dialog/add-quest-dialog/add-quest-dialog.component.scss
src/app/ui/dialog/add-quest-dialog/add-quest-dialog.component.ts
src/app/ui/dialog/dialog.module.ts
src/app/ui/members-quest-approval/members-quest-approval.component.html
src/app/ui/members-quest-approval/members-quest-approval.component.ts
src/app/ui/members-quest-approval/quest-approval-dialog.component.html
src/app/ui/player-quest-list/player-quest-list.component.html
src/app/ui/player-quest-list/player-quest-list.component.scss
src/app/ui/player-quest-list/player-quest-list.component.ts
src/app/ui/player-quest-list/submit-quest-dialog.component.html
src/app/ui/player-quest/player-quest.d.ts
src/app/ui/team-page/team-page.component.html
src/app/ui/team-page/team-page.component.ts
src/app/ui/user-login/user-login.component.html
src/app/ui/user-login/user-login.component.scss
src/app/ui/user-login/user-login.component.ts
src/app/ui/user-profile/user-profile.component.html
src/app/ui/user-profile/user-profile.component.scss
src/app/ui/user-profile/user-profile.component.ts

**Tested the ff cases:**
1. Adding player quests via new quests
2. Adding player quests via existing core tag quest
3. Player quest update/ delete
4. Quest submission
5. Quest Approval/Rejection
**New Search Algo:**
1. keyword array will be stored in quest document containing lower-cased words from the quest name
2. quest searching will be done using array-contains
Example:
quest with name "Infor Landmark Certified Developer" will have keywords: ["infor", "landmark", "certified", "developer"]

resolves #11

---

src/app/teams/teams.service.ts
src/app/ui/members-quest-approval/members-quest-approval.component.html
src/app/ui/members-quest-approval/members-quest-approval.component.scss
src/app/ui/members-quest-approval/members-quest-approval.component.ts

adding the team selection in the manage quests page

closes #16

---

src/app/ui/team-page/team-members/team-members.component.html
src/app/ui/team-page/team-members/team-members.component.ts

closes #42
Apologies, this is untested, currently cannot have leaderboard install proper dependencies with node version in my home laptop. Will test ASAP, but the idea is all here, comments and suggestions are welcome.

Disable navigation to leads

---

src/app/ui/dialog/add-quest-dialog/add-quest-dialog.component.html
src/app/ui/dialog/add-quest-dialog/add-quest-dialog.component.ts

This fixes the remaining bugs found in #11 :
1. Quest Name and Source should only accept alphanumeric with spaces
2. Quest Name and Source should not accept spaces only
3. Accepted character length should fall between 3-50

Fixes remaining quest bugs

---

src/app/ui/dialog/add-quest-dialog/add-quest-dialog.component.scss
src/app/ui/dialog/add-quest-dialog/add-quest-dialog.component.ts
src/styles.scss
src/variables.scss

This fixes the quest change happening on the quest list even when the update button is not clicked.
Also removed new tagging for pure space characters entered on the quest field.
Added a more visible gray highlight for the select dropdown options

fixes quest update bug

---

angular.json
package.json
src/app/ui/dialog/add-quest-dialog/add-quest-dialog.component.ts

adjusted staging build config to align with production

fixed access error to properties and method,

---

src/app/app.component.html
src/app/app.component.scss
src/app/core/auth.service.ts
src/app/ui/home-page/home-page.component.html
src/app/ui/player-quest-list/player-quest-list.component.ts
src/index.html
src/styles.scss

Closes #69 & changed leaderboard title

---

src/app/core/email.service.ts
src/environments/environment.prod.ts

added rewards.recognitionph@infor.com as default email recipient

closes #63 adding a default cc to the email list

---

src/app/app.module.ts
src/app/core/auth.service.ts
src/app/core/cache-reuse-strategy.ts
src/app/ui/home-page/home-page.component.ts

additionally removed season id read from homepage

Closes #83 Cache visited routes

---

src/app/ui/join-team-page/join-team-page.component.ts

Change join a team prompt message

---

src/app/ui/dialog/add-quest-dialog/add-quest-dialog.component.ts
src/app/ui/user-profile/user-profile.component.ts

Added new regex rule

---

src/app/ui/season-rank.pipe.ts
src/app/ui/user-profile/user-profile.component.html

New season ranking mechanics

---

src/app/ui/player-quest/counter.d.ts
src/app/ui/player-quest/monthly-counter.d.ts
src/app/ui/player-quest/player-points.d.ts
src/app/ui/player-quest/player-quest.service.ts
src/app/ui/ui.module.ts

Initial monthly counter added to player points

Closes #106

---

src/app/ui/home-page/home-page.component.html
src/app/ui/home-page/home-page.component.ts
src/app/ui/player-quest/player-points.d.ts
src/app/ui/player-quest/player-quest.d.ts
src/app/ui/player-quest/player-quest.service.ts
src/app/ui/user-profile/user-profile.component.ts

This commit will add the team name into the top players list. I've attached the script which is needed to be executed for the functionality to fully take effect. For the person who will be executing the script, kindly update the database url so that the changes will be pushed into the production server. This script has already been applied to the staging database.
[update-player-poinst-team-name-script.zip](https://github.com/nbcp/leaderboard/files/3651056/update-player-poinst-team-name-script.zip)

closes #110

---

src/app/quests/quest.service.ts
src/app/ui/dialog/add-quest-dialog/add-quest-dialog.component.html
src/app/ui/dialog/add-quest-dialog/add-quest-dialog.component.ts
src/app/ui/dialog/add-quest-dialog/add-quest-dialog.service.ts
src/app/ui/player-quest/player-quest.service.ts
src/app/ui/user-profile/user-profile.component.ts
src/environments/environment.prod.ts
src/environments/environment.ts

This release would include the ff:
- #125 Scholar Badge 
- #126 Quest Assignment Bug
- #127 Allow only one required quest per category

October Sprint Release

---

src/app/badges/badge/badge-image.component.scss
src/app/badges/badges.service.ts
src/app/ui/player-quest/player-quest.service.ts
src/environments/environment.prod.ts
src/environments/environment.ts

This introduces 2 new badges:
- Outstanding work! #96
- Well done! #98 
Note: Please test all other badges as well for possible regressions.

November Sprint Release
